#Constant values
$SUBTITLES_BOTH = "BOTH"
$SUBTITLES_DOWNLOAD = "DOWNLOAD"
$SUBTITLES_EMBED = "EMBED"

#monitoredHash primary keys
$ARCHIVE_TXT_KEY = "ARCHIVE_TXT"
$AUDIO_ONLY_KEY = "AUDIO_ONLY"
$COOKIES_BROWSER_KEY = "COOKIES_BROWSER"
$COOKIES_FILE_KEY = "COOKIES_FILE"
$DIRECTORY_KEY = "DIRECTORY"
$FILENAME_CONVENTION_KEY = "FILENAME_CONVENTION"
$LABEL_KEY = "LABEL"
$MATCH_TITLE_KEY = "MATCH_TITLE"
$MUSIC_KEY = "MUSIC"
$REJECT_TITLE_KEY = "REJECT_TITLE"
$SUBTITLES_KEY = "SUBTITLES"
$SUBTITLES_REQUIRED_KEY = "SUBTITLES_REQUIRED"
$URL_KEY = "URL"

. $PSScriptRoot\ytAutoDownload_user_constants.ps1